# Run automated setup steps: verify pipeline, theme pull, merge brand (no push), write SETUP_STATUS.
# Run from repo root. Use after guru review/audit to finish what can be automated.
# Requires: .env.local with SHOPIFY_STORE_DOMAIN; SHOPIFY_CLI_THEME_TOKEN or SHOPIFY_ACCESS_TOKEN for non-interactive pull.

param(
    [string]$Store = $env:SHOPIFY_STORE_DOMAIN,
    [switch]$SkipVerify = $false,
    [switch]$SkipPull = $false,
    [switch]$SkipMerge = $false
)

$ErrorActionPreference = "Stop"

$repoPath = if ($PSScriptRoot) {
    $parent = Join-Path $PSScriptRoot ".."
    (Resolve-Path (Join-Path $parent "..")).Path
} else {
    (Get-Location).Path
}
Set-Location $repoPath

if (Test-Path ".env.local") {
    Get-Content ".env.local" | ForEach-Object {
        $line = $_.Trim()
        if ($line -and -not $line.StartsWith("#") -and $line -match "^([^=]+)=(.*)$") {
            [Environment]::SetEnvironmentVariable($matches[1].Trim(), $matches[2].Trim(), "Process")
        }
    }
}
if ([string]::IsNullOrWhiteSpace($Store)) { $Store = $env:SHOPIFY_STORE_DOMAIN }

$statusPath = Join-Path $repoPath "docs\status\SETUP_STATUS.md"

Write-Host "=== Finish setup (automated steps) ===" -ForegroundColor Cyan
Write-Host ""

$pullOk = $false
$mergeOk = $false
$verifyOk = $false

# 1. Pipeline verification
if (-not $SkipVerify) {
    Write-Host "[1/4] Pipeline verification..." -ForegroundColor Yellow
    & "$repoPath\scripts\verify-pipeline.ps1" -SkipRunbook
    $verifyOk = ($LASTEXITCODE -eq 0)
    Write-Host ""
} else {
    Write-Host "[1/4] Pipeline verification skipped." -ForegroundColor Gray
    $verifyOk = $true
}

# 2. Theme pull
if (-not $SkipPull -and $Store) {
    Write-Host "[2/4] Theme pull..." -ForegroundColor Yellow
    & "$PSScriptRoot\theme-pull.ps1" -Store $Store
    $pullOk = ($LASTEXITCODE -eq 0)
    Write-Host ""
} else {
    Write-Host "[2/4] Theme pull skipped (SkipPull or no Store)." -ForegroundColor Gray
}

# 3. Merge brand + copy images (no push)
if (-not $SkipMerge) {
    Write-Host "[3/4] Merge brand and copy images (no push)..." -ForegroundColor Yellow
    & "$PSScriptRoot\theme-update-store.ps1" -Store $Store -SkipPush
    $mergeOk = ($LASTEXITCODE -eq 0)
    Write-Host ""
} else {
    Write-Host "[3/4] Merge skipped." -ForegroundColor Gray
    $mergeOk = $true
}

# 4. Write SETUP_STATUS.md
Write-Host "[4/4] Writing docs/status/SETUP_STATUS.md..." -ForegroundColor Yellow

$themeRoot = Join-Path (Join-Path (Join-Path (Join-Path $repoPath "src") "shopify") "themes") "aodrop-theme"
$layoutExists = Test-Path (Join-Path (Join-Path $themeRoot "layout") "theme.liquid")

$nextSteps = @()
if (-not $pullOk) {
    $nextSteps += "- **Theme pull** failed (SSL/network or auth). Retry: `.\scripts\shopify\theme-pull.ps1` or run `.\scripts\shopify\theme-auth-then-pull.ps1` or `.\scripts\shopify\theme-auth-via-browser.ps1`, then run this script again."
} else {
    $nextSteps += "- **Theme pull** succeeded."
}
if ($pullOk -and -not $layoutExists) {
    $nextSteps += "- Theme folder still missing `layout/theme.liquid` (pull may have been partial). Run theme-pull again or check network."
}
if ($pullOk -and $layoutExists) {
    $nextSteps += "- **Preview:** Run `.\scripts\shopify\theme-dev.ps1` and confirm the preview loads."
    $nextSteps += "- **Admin:** Open https://aodrop.com/admin → Online store → Themes; confirm theme and GitHub connection if used."
    $nextSteps += "- **Optional (push to store):** Run `.\scripts\shopify\theme-update-store.ps1` (use `-Live` only when updating live)."
}

$content = @"
# Setup status (auto-generated by finish-setup.ps1)

**Last run:** $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")

## Automated steps

| Step              | Result   |
| ----------------- | -------- |
| Pipeline verify   | $(if ($verifyOk) { "OK" } else { "FAIL" }) |
| Theme pull        | $(if ($SkipPull) { "skipped" } elseif ($pullOk) { "OK" } else { "FAIL" }) |
| Merge brand (no push) | $(if ($SkipMerge) { "skipped" } elseif ($mergeOk) { "OK" } else { "FAIL" }) |
| Full theme (layout/theme.liquid) | $(if ($layoutExists) { "yes" } else { "no" }) |

## Next steps

$(($nextSteps | ForEach-Object { $_ }) -join "`n")

See: [MANUAL_VERIFICATION_CHECKLIST.md](MANUAL_VERIFICATION_CHECKLIST.md), [docs/UPDATE_SHOPIFY_FROM_CURSOR.md](../UPDATE_SHOPIFY_FROM_CURSOR.md).
"@

$content | Out-File -FilePath $statusPath -Encoding UTF8
Write-Host "[OK] Wrote $statusPath" -ForegroundColor Green
Write-Host ""

if (-not $verifyOk) {
    Write-Host "Pipeline verification had failures. Fix and re-run." -ForegroundColor Yellow
    exit 1
}
if (-not $pullOk -and -not $SkipPull) {
    Write-Host "Theme pull failed (SSL/network or auth). When ready: run theme-auth-then-pull.ps1 or theme-auth-via-browser.ps1, then theme-pull.ps1 or finish-setup.ps1." -ForegroundColor Yellow
    Write-Host "Merge and SETUP_STATUS were still applied. See docs/status/SETUP_STATUS.md for next steps." -ForegroundColor Cyan
    exit 0
}
Write-Host "Setup steps complete. See docs/status/SETUP_STATUS.md for next steps." -ForegroundColor Green
exit 0
